[package]
name = "packed_struct_nostd_tests"
version = "0.1.0"
authors = ["Rudi Benkovic <rudi.benkovic@gmail.com>"]

[dependencies]
packed_struct = { path = "../packed_struct/", version = "0.10", default-features = false }